# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘CollectionViewServerRealm’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Networking
  pod 'Alamofire', '~> 4.3’

  pod 'Kingfisher', '~> 3.0'

  pod 'ObjectMapper', '~> 2.2'

  pod 'RealmSwift'
 
end
